# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# ESLint is a tool for identifying and reporting on patterns
# found in ECMAScript/JavaScript code.
# More details at https://github.com/eslint/eslint
# and https://eslint.org

name: ESLint

on:
  push:
    branches:
      - Experimental
      - master

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.x ]

    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache
        uses: actions/cache@v4.0.0
        with:
          path: node_modules
          key: ${{ runner.os }}-devbuild-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-devbuild-${{ env.cache-name }}-

      - name: Install modules
        run: npm ci

      - name: Run ESLint
        run: eslint .
